"""
Hi everyone, this is the code file for you to do your comprehension exercise & assignment (the base).
Of course, don't modify this py file directly, instead, create a separate one in your working folder.
Remember to commit them.

Library requirements:
sys
collections
pathlib
numpy
sklearn
pandas
matplotlib
joblib

Responsible AI usage note: this code is generated by AI with human supervision and assistance.
The notes dropped down here are written by human.
"""
import sys
from collections import Counter
from pathlib import Path
import numpy as np
import sklearn #What is sklearn? Why do we use it?
from sklearn import datasets, metrics
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.dummy import DummyClassifier
from sklearn.ensemble import RandomForestClassifier #Can you explain what is Random Forest Classifier?
from sklearn.inspection import permutation_importance
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import (
    GridSearchCV,
    cross_validate,
    train_test_split,
)
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
# Originally, suggested by ai, it is said that this part should be defensive importation. However, I expect you to proofread the whole code successfully, so no defensive importation.
import pandas as pd
import matplotlib
matplotlib.use("Agg")  #Can you explain what's the purpose of this line? Why do we use "Agg" here?
#With reference to this documentation: https://matplotlib.org/stable/api/matplotlib_configuration_api.html#matplotlib.use
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay
import joblib

HAS_MATPLOTLIB = True
RANDOM_STATE = 42 #The random state here is set to 42 on purpose. Maintaining the standard while ensuring the same results!
OUTPUT_DIR = Path(__file__).resolve().parent / "outputs"
def banner(title: str) -> None: #I acutally don't quite understand why ai suggested a "good" formatting. But never mind.
    print("\n" + "=" * 74)
    print(title)
    print("=" * 74)

def main() -> None:
    banner("0. ENVIRONMENT") #Mainly for me to debug your environment, this part is negligible for content.
    print(f"Python       : {sys.version.split()[0]}")
    print(f"scikit-learn : {sklearn.__version__}")
    print(f"numpy        : {np.__version__}")
    print(f"pandas       : {pd.__version__}")

    # =======================================================================
    # 1. LOAD THE DATA
    # =======================================================================
    # load_iris() returns:
    #   X            : feature matrix, shape (150, 4)
    #   y            : integer labels 0/1/2, shape (150,)
    #   feature_names: the 4 column names
    #   target_names : the 3 class names, in the same order as the integers
    load = datasets.load_iris() #Take it easy, it's just a dataset!!! Definitely not me wanna to be lazy so choosing an existing one.
    X = load.data
    y = load.target
    feature_names = [str(name) for name in load.feature_names]
    class_names = [str(name) for name in load.target_names]

    banner("1. EXPLORE THE DATA")
    print(f"X shape (samples, features) : {X.shape}")
    print(f"y shape (labels)            : {y.shape}")
    print(f"Features                    : {feature_names}")
    print(f"Classes                     : {class_names}")
    print(f"Label values                : {sorted(set(y.tolist()))}")

    #Balcning each class, ensuring fair test and accuracy.
    counts = Counter(y.tolist())
    print("\nClass balance:")
    for label, count in sorted(counts.items()):
        pct = 100.0 * count / len(y)
        print(f"  {label} = {class_names[label]:<12} {count:>4} samples")
    print("Can you observe whether this dataset is balanced? If yes, why? If not, what is the reason?")

    #Data splitting steps.
    #This part is VERY pivotal. For data splitting, two sets of data is a must: training set and testing set.
    #Lemme do a metaphor. Training set is like assignments, testing set is like the final exam. Sometimes, some more testing set can be included to act as the responsibility as quiz/test.
    banner("2. TRAIN / TEST SPLIT")
    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.20,       # 20% held out for the final evaluation
        stratify=y,           # preserve class proportions (important!)
        random_state=RANDOM_STATE,
    )
    print(f"Training set : {X_train.shape[0]} samples")
    print(f"Test set     : {X_test.shape[0]} samples")
    print(f"Train class counts: {dict(sorted(Counter(y_train.tolist()).items()))}")
    print(f"Test  class counts: {dict(sorted(Counter(y_test.tolist()).items()))}")
    print("Why does the propotion of each class the same? Did we set anythign to ensure?")

    # Baseline time! Use dummy classifier to see how well we can do with a simple model!
    banner("3. BASELINE (DummyClassifier)")
    dummy = DummyClassifier(strategy="most_frequent", random_state=RANDOM_STATE)
    dummy.fit(X_train, y_train)
    dummy_acc = dummy.score(X_test, y_test)
    print(f"Dummy test accuracy: {dummy_acc:.4f}")
    print("What is the baseline in this case? Why do we need a baseline? What is the purpose of this baseline?")

    #1st model.
    banner("4. FIRST MODEL: StandardScaler -> LogisticRegression")

    log_reg = Pipeline(
        steps=[
            ("scaler", StandardScaler()),
            ("clf", LogisticRegression(max_iter=1000, random_state=RANDOM_STATE)),
        ]
    )
    log_reg.fit(X_train, y_train)
    y_pred = log_reg.predict(X_test)

    print(f"Train accuracy: {log_reg.score(X_train, y_train):.4f}")
    print(f"Test  accuracy: {log_reg.score(X_test, y_test):.4f}")
    print("Does this model overfit (Train high test low situation)? Explain. Hence, what is a possible reason behind overfitting?")
    cm = metrics.confusion_matrix(y_test, y_pred)
    print("\nConfusion matrix (rows = actual, columns = predicted):")
    print(f"{'':<14}" + "".join(f"{n:>12}" for n in class_names))
    for i, name in enumerate(class_names):
        print(f"{name:<14}" + "".join(f"{v:>12}" for v in cm[i]))
    print("\nClassification report:")
    print(metrics.classification_report(y_test, y_pred, target_names=class_names))
    print("Where does our model get confused?")

    # Using K fold to ensure the model! (Perhaps the same stuff as PyroForge)
    banner("5. COMPARE CLASSIFIERS (5-fold cross-validation on the TRAIN set)")

    models = {
        "Logistic Regression": Pipeline(
            [("scaler", StandardScaler()),
             ("clf", LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))]
        ),
        "k-NN (k=5)": Pipeline(
            [("scaler", StandardScaler()),
             ("clf", KNeighborsClassifier(n_neighbors=5))]
        ),
        "Decision Tree (unlimited)": Pipeline(
            [("scaler", StandardScaler()),
             ("clf", DecisionTreeClassifier(random_state=RANDOM_STATE))]
        ),
        "Decision Tree (max_depth=3)": Pipeline(
            [("scaler", StandardScaler()),
             ("clf", DecisionTreeClassifier(max_depth=3, random_state=RANDOM_STATE))]
        ),
        "Random Forest (200 trees)": Pipeline(
            [("scaler", StandardScaler()),
             ("clf", RandomForestClassifier(
                 n_estimators=200, random_state=RANDOM_STATE))]
        ),
        "Gaussian Naive Bayes": Pipeline(
            [("scaler", StandardScaler()), ("clf", GaussianNB())]
        ),
        "Linear Discriminant Analysis": Pipeline(
            [("scaler", StandardScaler()), ("clf", LinearDiscriminantAnalysis())]
        ),
    }

    scoring = ["accuracy", "f1_macro"]
    cv_results = {}

    header = (f"{'model':<30}{'train acc':>11}{'CV acc (mean+/-std)':>24}"
              f"{'CV F1 macro (mean+/-std)':>27}")
    print(header)
    print("-" * len(header))
    for name, model in models.items():
        res = cross_validate(
            model, X_train, y_train, cv=5, scoring=scoring,
            return_train_score=True,   # so that overfitting is visible below
        )
        train_acc = res["train_accuracy"].mean()
        acc, acc_sd = res["test_accuracy"].mean(), res["test_accuracy"].std()
        f1, f1_sd = res["test_f1_macro"].mean(), res["test_f1_macro"].std()
        cv_results[name] = {
            "train_acc": train_acc, "acc": acc, "acc_sd": acc_sd,
            "f1": f1, "f1_sd": f1_sd,
        }
        print(f"{name:<30}{train_acc:>11.4f}{acc:>13.4f} +/- {acc_sd:<7.4f}"
              f"{f1:>15.4f} +/- {f1_sd:<7.4f}")

    best_name = max(cv_results, key=lambda n: (cv_results[n]["f1"], cv_results[n]["acc"]))
    print("Which of the model is the best-performing one in F1 macro? Does a high accuracy in training set mean higher accuracy in CV? Why?")
    print("Suggest a model which is overfitting. How do you know?")

    # After choosing the best performing model, we can evaluate it on the test set.
    banner(f"6. FINAL TEST-SET EVALUATION: {best_name}") #Don't just copy the answer here. Try to explain and understand yourself.

    best_model = models[best_name]
    best_model.fit(X_train, y_train)
    y_pred_best = best_model.predict(X_test)

    train_acc = best_model.score(X_train, y_train)
    test_acc = best_model.score(X_test, y_test)
    print(f"Train accuracy : {train_acc:.4f}")
    print(f"Test  accuracy : {test_acc:.4f}")
    print(f"Gap            : {train_acc - test_acc:+.4f}  ")
    print("What does a large positive gap mean?")

    print("\nConfusion matrix (rows = actual, columns = predicted):")
    print(f"{'':<14}" + "".join(f"{n:>12}" for n in class_names))
    cm_best = metrics.confusion_matrix(y_test, y_pred_best)
    for i, name in enumerate(class_names):
        print(f"{name:<14}" + "".join(f"{v:>12}" for v in cm_best[i]))

    print("\nClassification report:")
    print(metrics.classification_report(y_test, y_pred_best, target_names=class_names))

    # --- What the individual numbers mean ---------------------------------
    macro_f1 = metrics.f1_score(y_test, y_pred_best, average="macro")
    print(f"Accuracy      : {metrics.accuracy_score(y_test, y_pred_best):.4f}")
    print(f"F1 (macro)    : {macro_f1:.4f}")
    print("Deduce the performance of the best-performing model.")

    # Tuning the hyperparameter(ssssss).
    banner("7. HYPERPARAMETER TUNING (GridSearchCV on the TRAIN set)")

    tuning_pipeline = Pipeline(
        [("scaler", StandardScaler()),
         ("clf", LogisticRegression(max_iter=1000, random_state=RANDOM_STATE))]
    )
    param_grid = {
        "clf__C": [0.01, 0.1, 1.0, 10.0, 100.0],
        "clf__solver": ["lbfgs", "newton-cg"],
    }
    grid = GridSearchCV(
        tuning_pipeline,
        param_grid=param_grid,
        cv=5,
        scoring="f1_macro",
        n_jobs=1, #You can multi-task if you're confident with your computer.
        refit=True,
    )
    grid.fit(X_train, y_train)

    print(f"Configurations tried : {len(grid.cv_results_['params'])}")
    print(f"Best parameters      : {grid.best_params_}")
    print(f"Best CV F1 (macro)   : {grid.best_score_:.4f}")
    print(f"Test accuracy        : {grid.score(X_test, y_test):.4f}")
    print(f"Test F1 (macro)      : "
          f"{metrics.f1_score(y_test, grid.predict(X_test), average='macro'):.4f}")
    top = np.argsort(grid.cv_results_["rank_test_score"])[:5]
    print("\nTop 5 configurations:")
    for i in top:
        p = grid.cv_results_["params"][i]
        m = grid.cv_results_["mean_test_score"][i]
        s = grid.cv_results_["std_test_score"][i]
        print(f"  F1 {m:.4f} +/- {s:.4f}   C={p['clf__C']:<8} solver={p['clf__solver']}")
    print("What is the benefit of outputting multiple 'best' configurations?")

    # Inspection! You can now "Check" your model.
    banner("8. INTERPRETATION / FEATURE IMPORTANCE")
    final_estimator = grid.best_estimator_
    if hasattr(final_estimator, "named_steps") and "clf" in final_estimator.named_steps:
        clf = final_estimator.named_steps["clf"]
        if hasattr(clf, "coef_"):
            print("Logistic Regression coefficients (one row per class):")
            print(f"{'feature':<22}" + "".join(f"{n:>13}" for n in class_names))
            for i, fname in enumerate(feature_names):
                print(f"{fname:<22}" + "".join(f"{c:>13.3f}" for c in clf.coef_[:, i]))
            print("What is the meaning of a high magnitude?")

    perm = permutation_importance(
        final_estimator, X_test, y_test,
        n_repeats=20, random_state=RANDOM_STATE, scoring="accuracy",
    )
    print("\nPermutation importance (drop in accuracy when a feature is shuffled):")
    order = np.argsort(perm.importances_mean)[::-1]
    for i in order:
        print(f"  {feature_names[i]:<22} {perm.importances_mean[i]:+.4f} "
              f"+/- {perm.importances_std[i]:.4f}")
    print("What is the meaning of a high permutation importance?")

    # Save model! Congrats!!!!
    banner("9. SAVE / LOAD THE MODEL")

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    model_path = OUTPUT_DIR / "iris_classifier.joblib"

    joblib.dump(final_estimator, model_path)
    size_kb = model_path.stat().st_size / 1024
    print(f"Saved to      : {model_path}")
    print(f"File size     : {size_kb:.1f} KB")
    reloaded = joblib.load(model_path)
    same = np.array_equal(reloaded.predict(X_test), final_estimator.predict(X_test))
    print(f"Reloaded model predicts identically: {same}")
    print("Why reloading?")
    banner("10. PREDICT ON NEW SAMPLES")

    new_samples = np.array(
        [
            [5.1, 3.5, 1.4, 0.2],   # looks like setosa
            [6.0, 2.7, 5.1, 1.6],   # looks like versicolor / virginica
            [7.6, 3.0, 6.6, 2.1],   # looks like virginica
        ]
    )

    predictions = reloaded.predict(new_samples)
    probabilities = reloaded.predict_proba(new_samples)

    print(f"{'sepal_l':>8}{'sepal_w':>9}{'petal_l':>9}{'petal_w':>9}   "
          f"{'prediction':<12}{'confidence':>11}")
    for row, pred, probs in zip(new_samples, predictions, probabilities):
        print(f"{row[0]:>8.1f}{row[1]:>9.1f}{row[2]:>9.1f}{row[3]:>9.1f}   "
              f"{class_names[pred]:<12}{probs[pred]:>11.1%}")
        print("           probabilities: "
              + ", ".join(f"{n}={p:.3f}" for n, p in zip(class_names, probs)))

    print("Explain the confidence level.")

    # Graphical time!!!!!!!
    banner("11. PLOTS")
    if True:  # HAS_MATPLOTLIB, I assume you have it.
        # --- (a) Confusion matrix -----------------------------------------
        fig, ax = plt.subplots(figsize=(5.5, 4.5))
        ConfusionMatrixDisplay.from_estimator(
            reloaded, X_test, y_test,
            display_labels=class_names,
            cmap="Blues", colorbar=False, ax=ax,
        )
        ax.set_title(f"Confusion matrix -- {best_name}\n(test set, n={len(y_test)})")
        fig.tight_layout()
        cm_path = OUTPUT_DIR / "confusion_matrix.png"
        fig.savefig(cm_path, dpi=140)
        plt.close(fig)
        print(f"Saved {cm_path}")

        # --- (b) Feature importances --------------------------------------
        fig, ax = plt.subplots(figsize=(6.5, 4.0))
        y_pos = np.arange(len(feature_names))
        ax.barh(y_pos, perm.importances_mean, xerr=perm.importances_std,
                color="#4c72b0", edgecolor="black", linewidth=0.5)
        ax.set_yticks(y_pos)
        ax.set_yticklabels(feature_names)
        ax.invert_yaxis()
        ax.set_xlabel("Mean drop in accuracy when the feature is shuffled")
        ax.set_title("Permutation importance (test set)")
        ax.axvline(0, color="grey", linewidth=0.8)
        fig.tight_layout()
        imp_path = OUTPUT_DIR / "feature_importance.png"
        fig.savefig(imp_path, dpi=140)
        plt.close(fig)
        print(f"Saved {imp_path}")
main()

print("Move on to hw.md for the assignment questions in short.")